print("Her kan du legge sammen en prosessor og hovedkort for å finne ut om de er kompatible")
print("Programmet fungerer bare med Intel 14 13 12 eller AMD Ryzen")

intel_generasjon = None
amd_generasjon = None
hovedkort_info = None

valg_prosessor = int(input("Skriv inn tallet for prosessoren du har:\n 1) Intel\n 2) AMD Ryzen\n"))

if valg_prosessor == 1:
    intel_generasjon = input("Hva er generasjonen til Intel-prosessoren? ")
    hovedkort_info = input("Skriv inn navet til hovedkortet: ")

    kompatible_hovedkort_intel = [
        "Gigabyte Z790 AORUS ELITE AX ATX LGA1700",
        "MSI B760 GAMING PLUS WIFI ATX LGA1700",
        "MSI MAG Z790 TOMAHAWK WIFI ATX LGA1700",
        "MSI PRO B760-P",
        "Asus ROG MAXIMUS Z790 DARK HERO",
        "MSI PRO Z790-A MAX",
        "MSI PRO Z790-P",
        "Asus ROG STRIX B760-I",
        "Asus ROG STRIX Z790-A",
        "MSI PRO B760M-P",
        "Asus TUF GAMING Z790-PLUS",
        "Asus ROG STRIX Z790-E",
        "Gigabyte B760M DS3H AX Micro",
        "Gigabyte Z790 AORUS ELITE X",
        "Asus ROG STRIX Z790-E",
        "MSI MAG B760 TOMAHAWK",
        "NZXT N7 Z790 ATX",
        "Asus PRIME B760-PLUS",
        "Asus PRIME Z790-A WIFI ATX",
        "Gigabyte Z790 AORUS PRO X ATX LGA",
        "Gigabyte B760M DS3H",
        "Gigabyte B760 GAMING X AX ATX",
        "Asus TUF GAMING Z790-PLUS",
        "MSI PRO B760M-A",
        "Asus PRIME Z790-P",
        "Asus ROG STRIX B760-A",
        "MSI PRO Z790-A",
        "MSI MAG B760 TOMAHAWK",
        "Asus ROG STRIX Z790-H",
        "MSI MEG Z790 GODLIKE MAX EATX",
        "MSI Z790 GAMING PRO",
        "Asus ROG MAXIMUS Z790 FORMULA ATX",
        "ASRock B760M-HDV/M.2",
        "Gigabyte Z790 UD AC ATX",
        "MSI MPG Z790 EDGE",
        "Asus TUF GAMING Z790-PRO",
        "Asus ROG STRIX B760-A",
        "ASRock B760M PG SONIC",
        "Asus ROG MAXIMUS Z790 HERO",
        "ASRock B760M Steel Legend",
        "NZXT N7 Z790 ATX",
        "ASRock B760M-H/M.2",
        "Asus PRIME Z790-V",
        "Gigabyte Z790 AORUS ELITE AX ICE",
        "MSI PRO Z790-S",
        "ASRock B760 Pro RS/D4",
        "ASRock Z790 PG LIGHTNING",
        "Asus ROG STRIX Z790-A",
        "MSI MPG Z790I",
        "Gigabyte H610M S2H",
        "Gigabyte Z790 GAMING X",
        "MSI PRO B760M-A",
        "Asus ProArt Z790-CREATOR",
        "Gigabyte B760 AORUS ELITE",
        "Asus ROG STRIX Z790-I",
        "MSI MAG Z790 TOMAHAWK MAX",
        "ASRock B760M PG Lightning",
        "MSI MPG Z790 EDGE TI MAX",
        "ASRock B760M-HDV/M.2 D4",
        "Asus PRIME Z790-P",
        "Asus ROG STRIX Z790-F",
        "MSI MPG Z790 CARBON",
        "MSI MPG B760I EDGE",
        "Gigabyte B760M AORUS ELITE",
        "Gigabyte B760I AORUS PRO Mini",
        "Asus TUF GAMING B760M-PLUS",
        "ASRock B760M PG Riptide",
        "Gigabyte Z790 UD AX",
        "ASRock B760M Pro RS Micro",
        "ASRock B760M Pro RS/D4",
        "Gigabyte Z790 AORUS ELITE X AX",
        "MSI MAG Z790 TOMAHAWK",
        "Asus ROG MAXIMUS Z790 APEX ENCORE",
        "MSI MEG Z790 GODLIKE",
        "Gigabyte B760M C",
        "Asus TUF GAMING B760-PLUS",
        "Gigabyte B760I AORUS PRO",
        "ASRock B760 Pro RS",
        "Asus ROG STRIX B760-F",
        "Asus TUF GAMING B760M-PLUS",
        "Gigabyte Z790 AORUS XTREME X",
        "Gigabyte Z690 AORUS ELITE AX",
        "Asus TUF GAMING B760-PLUS",
        "Gigabyte B760 DS3H AC",
        "Asus PRIME B760M-A",
        "MSI MAG B760M MORTAR",
        "ASRock Z790M-ITX WIFI",
        "Asus PRIME Z790M-PLUS",
        "Gigabyte Z790I AORUS ULTRA",
        "Gigabyte Z790 AORUS MASTER MOTHERBOARD",
        "ASRock Z790 Nova",
        "Asus PRIME B760-PLUS",
        "Gigabyte Z790 AORUS MASTER X",
        "Gigabyte Z790 D MOTHERBOARD",
        "ASRock Z790 Pro RS",
        "ASRock B760M",
        "Asus ROG STRIX Z790-A",
        "MSI Z790 GAMING PLUS"
     "gigabyte z790 aorus elite ax atx lga1700",
    "msi b760 gaming plus wifi atx lga1700",
    "msi mag z790 tomahawk wifi atx lga1700",
    "msi pro b760-p",
    "asus rog maximus z790 dark hero",
    "msi pro z790-a max",
    "msi pro z790-p",
    "asus rog strix b760-i",
    "asus rog strix z790-a",
    "msi pro b760m-p",
    "asus tuf gaming z790-plus",
    "asus rog strix z790-e",
    "gigabyte b760m ds3h ax micro",
    "gigabyte z790 aorus elite x",
    "asus rog strix z790-e",
    "msi mag b760 tomahawk",
    "nzxt n7 z790 atx",
    "asus prime b760-plus",
    "asus prime z790-a wifi atx",
    "gigabyte z790 aorus pro x atx lga",
    "gigabyte b760m ds3h",
    "gigabyte b760 gaming x ax atx",
    "asus tuf gaming z790-plus",
    "msi pro b760m-a",
    "asus prime z790-p",
    "asus rog strix b760-a",
    "msi pro z790-a",
    "msi mag b760 tomahawk",
    "asus rog strix z790-h",
    "msi meg z790 godlike max eatx",
    "msi z790 gaming pro",
    "asus rog maximus z790 formula atx",
    "asrock b760m-hdv/m.2",
    "gigabyte z790 ud ac atx",
    "msi mpg z790 edge",
    "asus tuf gaming z790-pro",
    "asus rog strix b760-a",
    "asrock b760m pg sonic",
    "asus rog maximus z790 hero",
    "asrock b760m steel legend",
    "nzxt n7 z790 atx",
    "asrock b760m-h/m.2",
    "asus prime z790-v",
    "gigabyte z790 aorus elite ax ice",
    "msi pro z790-s",
    "asrock b760 pro rs/d4",
    "asrock z790 pg lightning",
    "asus rog strix z790-a",
    "msi mpg z790i",
    "gigabyte h610m s2h",
    "gigabyte z790 gaming x",
    "msi pro b760m-a",
    "asus proart z790-creator",
    "gigabyte b760 aorus elite",
    "asus rog strix z790-i",
    "msi mag z790 tomahawk max",
    "asrock b760m pg lightning",
    "msi mpg z790 edge ti max",
    "asrock b760m-hdv/m.2 d4",
    "asus prime z790-p",
    "asus rog strix z790-f",
    "msi mpg z790 carbon",
    "msi mpg b760i edge",
    "gigabyte b760m aorus elite",
    "gigabyte b760i aorus pro mini",
    "asus tuf gaming b760m-plus",
    "asrock b760m pg riptide",
    "gigabyte z790 ud ax",
    "asrock b760m pro rs micro",
    "asrock b760m pro rs/d4",
    "gigabyte z790 aorus elite x ax",
    "msi mag z790 tomahawk",
    "asus rog maximus z790 apex encore",
    "msi meg z790 godlike",
    "gigabyte b760m c",
    "asus tuf gaming b760-plus",
    "gigabyte b760i aorus pro",
    "asrock b760 pro rs",
    "asus rog strix b760-f",
    "asus tuf gaming b760m-plus",
    "gigabyte z790 aorus xtreme x",
    "gigabyte z690 aorus elite ax",
    "asus tuf gaming b760-plus",
    "gigabyte b760 ds3h ac",
    "asus prime b760m-a",
    "msi mag b760m mortar",
    "asrock z790m-itx wifi",
    "asus prime z790m-plus",
    "gigabyte z790i aorus ultra",
    "gigabyte z790 aorus master motherboard",
    "asrock z790 nova",
    "asus prime b760-plus",
    "gigabyte z790 aorus master x",
    "gigabyte z790 d motherboard",
    "asrock z790 pro rs",
    "asrock b760m",
    "asus rog strix z790-a",
    "msi z790 gaming plus"
    ]

    if hovedkort_info in kompatible_hovedkort_intel:
        print("Prosessor og hovedkort er kompatible.")
    else:
        print("Prosessor og hovedkort er ikke kompatible.")

elif valg_prosessor == 2:
    amd_generasjon = input("Hva er generasjonen til AMD Ryzen-prosessoren? Hvis du ikke vet det, gå tilbake og sjekk hjelp: ")
    hovedkort_info = input("Skriv inn informasjon om hovedkortet: ")

    kompatible_hovedkort_amd = [
    "Gigabyte B650 AORUS ELITE",
    "Asus ROG STRIX B650-A",
    "MSI B650 GAMING PLUS",
    "Gigabyte B650 GAMING X MOTHERBOARD",
    "ASRock B650M Pro RS",
    "Asus ROG STRIX B650E-F",
    "ASRock B650M Pro RS",
    "MSI MAG X670E TOMAHAWK",
    "Asus TUF GAMING B650-PLUS",
    "Gigabyte B650M DS3H MOTHERBOARD",
    "ASRock B650I Lightning",
    "ASRock A620M Pro RS",
    "Gigabyte X670 AORUS ELITE",
    "Gigabyte B650M AORUS ELITE",
    "NZXT N7 B650E",
    "Gigabyte B650 AORUS ELITE",
    "Asus ROG STRIX B650E-I",
    "MSI PRO B650M-P",
    "Gigabyte X670E AORUS PRO X",
    "Gigabyte B650I AORUS ULTRA",
    "ASRock B650E PG RIPTIDE",
    "Gigabyte A620I MOTHERBOARD",
    "MSI PRO A620M-E",
    "Asus TUF GAMING X670E-PLUS",
    "NZXT N7 B650E",
    "ASRock X670E Steel Legend",
    "MSI PRO B650-S",
    "ASRock B650M-HDV/M.2",
    "Gigabyte B650M K Micro",
    "Asus PRIME X670E-PRO",
    "Asus ROG STRIX B650E-E",
    "Asus PRIME A620-PLUS",
    "ASRock A620I LIGHTNING",
    "Asus PRIME B650-PLUS",
    "ASRock X670E PG Lightning",
    "ASRock B650M PG RIPTIDE",
    "Gigabyte B650 Gaming",
    "Gigabyte X670E AORUS MASTER",
    "Gigabyte X670 GAMING X",
    "Asus TUF GAMING B650M-PLUS",
    "ASRock B650 LiveMixer",
    "Asus TUF GAMING A620M-PLUS",
    "ASRock B650 PG LIGHTNING",
    "Gigabyte B650M D3HP",
    "Gigabyte B650 AORUS ELITE",
    "Gigabyte A620M GAMING X",
    "Gigabyte B650M GAMING X",
    "Asus PRIME X670-P",
    "Gigabyte X670E AORUS XTREME",
    "Asus PRIME X670-P",
    "ASRock B650 PRO RS",
    "Asus PRIME B650M-A",
    "MSI X670E GAMING PLUS",
    "ASRock B650E Taichi Lite",
    "Asus TUF GAMING B650-PLUS",
    "ASRock X670E Pro RS",
    "ASRock B650E PG-ITX",
    "Gigabyte B650 AORUS PRO",
    "Asus TUF GAMING X670E-PLUS",
    "ASRock B650E STEEL LEGEND",
    "Asus TUF GAMING B650M-PLUS",
    "ASRock B650E TAICHI",
    "Gigabyte B650M AORUS PRO",
    "Asus TUF GAMING B650M-E",
    "Biostar B650EGTQ",
    "Asus ROG STRIX X670E-E",
    "Asus ROG CROSSHAIR X670E HERO",
    "Asus ROG STRIX X670E-F",
    "MSI MPG B650 CARBON",
    "Asus ROG STRIX X670E-F",
    "Asus ROG STRIX X670E-I"
    "gigabyte b650 aorus elite",
    "asus rog strix b650-a",
    "msi b650 gaming plus",
    "gigabyte b650 gaming x motherboard",
    "asrock b650m pro rs",
    "asus rog strix b650e-f",
    "asrock b650m pro rs",
    "msi mag x670e tomahawk",
    "asus tuf gaming b650-plus",
    "gigabyte b650m ds3h motherboard",
    "asrock b650i lightning",
    "asrock a620m pro rs",
    "gigabyte x670 aorus elite",
    "gigabyte b650m aorus elite",
    "nzxt n7 b650e",
    "gigabyte b650 aorus elite",
    "asus rog strix b650e-i",
    "msi pro b650m-p",
    "gigabyte x670e aorus pro x",
    "gigabyte b650i aorus ultra",
    "asrock b650e pg riptide",
    "gigabyte a620i motherboard",
    "msi pro a620m-e",
    "asus tuf gaming x670e-plus",
    "nzxt n7 b650e",
    "asrock x670e steel legend",
    "msi pro b650-s",
    "asrock b650m-hdv/m.2",
    "gigabyte b650m k micro",
    "asus prime x670e-pro",
    "asus rog strix b650e-e",
    "asus prime a620-plus",
    "asrock a620i lightning",
    "asus prime b650-plus",
    "asrock x670e pg lightning",
    "asrock b650m pg riptide",
    "gigabyte b650 gaming",
    "gigabyte x670e aorus master",
    "gigabyte x670 gaming x",
    "asus tuf gaming b650m-plus",
    "asrock b650 livemixer",
    "asus tuf gaming a620m-plus",
    "asrock b650 pg lightning",
    "gigabyte b650m d3hp",
    "gigabyte b650 aorus elite",
    "gigabyte a620m gaming x",
    "gigabyte b650m gaming x",
    "asus prime x670-p",
    "gigabyte x670e aorus xtreme",
    "asus prime x670-p",
    "asrock b650 pro rs",
    "asus prime b650m-a",
    "msi x670e gaming plus",
    "asrock b650e taichi lite",
    "asus tuf gaming b650-plus",
    "asrock x670e pro rs",
    "asrock b650e pg-itx",
    "gigabyte b650 aorus pro",
    "asus tuf gaming x670e-plus",
    "asrock b650e steel legend",
    "asus tuf gaming b650m-plus",
    "asrock b650e taichi",
    "gigabyte b650m aorus pro",
    "asus tuf gaming b650m-e",
    "biostar b650egtq",
    "asus rog strix x670e-e",
    "asus rog crosshair x670e hero",
    "asus rog strix x670e-f",
    "msi mpg b650 carbon",
    "asus rog strix x670e-f",
    "asus rog strix x670e-i"
    ]

    if hovedkort_info in kompatible_hovedkort_amd:
        print("Prosessor og hovedkort er kompatible.")
    else:
        print("Prosessor og hovedkort er ikke kompatible.")

else:
    print("Ugyldig valg for prosessoren. Avslutter programmet.")
